version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
    volumes:
      - ./db:/var/lib/mysql
    container_name: "mysql"
  flask-api:
    image: flask-api
    build: ./Flask_API/.
    ports:
      - 5000:5000
    depends_on:
      - db
  flask-fs:
    image: flask-fs
    build: ./Flask_FullStack/.
    ports:
      - 80:80
    depends_on:
      - db
  node-api:
    image: node-api
    build: ./Node_API/.
    ports:
      - 8080:8080
    depends_on:
      - db
  react:
    image: react
    build: ./react-frontend/.
    ports:
      - 3000:80
    depends_on:
      - node-api
